#!/bin/sh

# $FreeBSD$
# KEYWORD: firstboot
# PROVIDE: firstboot_realhost
# REQUIRE: FILESYSTEMS NETWORKING SERVERS DAEMON dhclient
# BEFORE: LOGIN

## Modified from cperciva's sysutils/firstboot-pkgs

# Add the following lines to /etc/rc.conf.local or /etc/rc.conf (in the disk
# image, since this only runs on the first boot) to enable this:
#
# firstboot_realhost_enable="YES"
#
# and set the HTTP_PROXY IP:PORT part in firstboot_realhost_squid, e.g.,
#
# firstboot_realhost_squid="192.168.255.201:3128"

. /etc/rc.subr

: ${firstboot_realhost_enable:="NO"}

name="firstboot_realhost"
rcvar=firstboot_realhost_enable
start_cmd="firstboot_realhost_run"
stop_cmd=":"

firstboot_realhost_run()
{

    # Count rc.d scripts
    nscriptso=`ls /usr/local/etc/rc.d | wc -l`

    ## Set HOME so we have the right HOME folder
    # echo "HOME var before: $HOME"
    HOME=/root
    export HOME
    ## set PATH so fres can find git
    PATH="/sbin:/bin:/usr/sbin:/usr/bin:/usr/games:/usr/local/sbin:/usr/local/bin:${HOME}/bin"
    export PATH
    # echo "HOME var after: $HOME"

    if [ "x" != "x${firstboot_realhost_squid}" ]; then
        echo "RUN: env SQUID=${firstboot_realhost_squid} setproxy"
                   env SQUID=${firstboot_realhost_squid} setproxy
    fi

    ## Setup the pf firewall
    echo "RUN: gdf"
               gdf

    echo "RUN: env PAGER=cat freebsd-update --not-running-from-cron fetch install"
               env PAGER=cat freebsd-update --not-running-from-cron fetch install

    ## Setup $HOME/git and more
    echo "RUN: fres"
               fres

    ## Create an ssh key
    if [ ! -e ${HOME}/.ssh/id_ed25519 ]; then
        echo "RUN: ssh-makeprivkey-ed25519"
                   ssh-makeprivkey-ed25519
    fi

    # Count rc.d scripts again
    nscriptsn=`ls /usr/local/etc/rc.d | wc -l`

    zfs snap -r pool@2_firstboot_done

    # If we have more scripts, request a reboot
    if [ $nscriptsn -ne $nscriptso ]; then
        echo "Requesting reboot after installing packages with rc.d scripts."
        touch ${firstboot_sentinel}-reboot
    fi
}

load_rc_config $name
run_rc_command "$1"
