#!/bin/sh

# $FreeBSD$
# KEYWORD: firstboot
# PROVIDE: firstboot_realhost
# REQUIRE: FILESYSTEMS NETWORKING SERVERS DAEMON LOGIN dhclient
# BEFORE: LOGIN

## Modified from cperciva's sysutils/firstboot-pkgs

# Add the following lines to /etc/rc.conf.local or /etc/rc.conf (in the disk
# image, since this only runs on the first boot) to enable this:
#
# firstboot_realhost_enable="YES"
#
# and set the HTTP_PROXY IP:PORT part in firstboot_realhost_squid, e.g.,
#
# firstboot_realhost_squid="192.168.255.201:3128"

. /etc/rc.subr

: ${firstboot_realhost_enable:="NO"}

name="firstboot_realhost"
rcvar=firstboot_realhost_enable
start_cmd="firstboot_realhost_run"
stop_cmd=":"

firstboot_realhost_run()
{

    # Count rc.d scripts
    nscriptso=`ls /usr/local/etc/rc.d | wc -l`

    echo "HOME var before: $HOME"
    HOME=/root
    export HOME
    echo "HOME var after: $HOME"

    if [ "x" != "x${firstboot_realhost_squid}" ]; then
        echo "set proxy"
        env SQUID=${firstboot_realhost_squid} /root/bin/setproxy
    fi

    echo "gdf sets up pf"
    /root/bin/gdf

    echo "fres sets up /root/bin/* and pkg installs"
    /root/bin/fres
    if [ -e /root/git/skel/bin/fres ]; then
        echo "prune /root/bin/"
        /bin/rm -r /root/bin/
        /bin/sh /root/git/skel/bin/fres
    fi

    echo "make root ssh key"
    if [ ! -e /root/.ssh/id_ed25519 ]; then
        /root/bin/ssh-makeprivkey-ed25519
    fi

    # Count rc.d scripts again
    nscriptsn=`ls /usr/local/etc/rc.d | wc -l`

    # If we have more scripts, request a reboot
    if [ $nscriptsn -ne $nscriptso ]; then
        echo "Requesting reboot after installing packages with rc.d scripts."
        touch ${firstboot_sentinel}-reboot
    fi
}

load_rc_config $name
run_rc_command "$1"
