#!/bin/sh

# $FreeBSD$
# PROVIDE: keypkg
# REQUIRE: FILESYSTEMS NETWORKING SERVERS DAEMON LOGIN
# BEFORE: iocage

# Add the following lines to /etc/rc.conf.local or /etc/rc.conf to enable this:
#
# keypkg_enable="YES"
#
# If you use a USB key with ZFS, the zpool name can be set with
#
# keypkg_zpool="key"
#
# If you use ssh keyservers:
#
# keypkg_ssh="one two three"
# keypkg_ssh_flags="-F $keypkg_ssh_config -o UserKnownHostsFile=/etc/keypkg/known_hosts -i /etc/keypkg/id_rsa"

. /etc/rc.subr

: ${keypkg_enable:="NO"}
: ${keypkg_export:="YES"}
: ${keypkg_tmpfsdir:="/tmp/tmpfs"}
: ${keypkg_file:=keypkg_$(hostname -s).smime}
: ${keypkg_key:="/etc/keypkg/key.pem"}
: ${keypkg_cert:="/etc/keypkg/cert.pem"}

name="keypkg"
rcvar=keypkg_enable
start_cmd="keypkg_run"
stop_cmd=":"

keypkg_run()
{

    # restrictive mask for new files
    umask 077

    # mount tmpfs to keep the passfile in ram
    mkdir -p $keypkg_tmpfsdir
    chmod 700 $keypkg_tmpfsdir
    mount -t tmpfs tmpfs $keypkg_tmpfsdir
    if ! mount | grep 'tmpfs on /tmp/tmpfs (tmpfs' >/dev/null 2>&1 ; then
        exit 1
    fi

    # Fetch keypkg_hostname.smime from usb key zpool or ssh
    if [ -n "$keypkg_zpool" ]; then
        if ! zpool list ${keypkg_zpool} >/dev/null 2>&1 ; then
            # if not already exist, import the pool on the USB thumbdrive
            zpool import ${keypkg_zpool}
        fi
        if zfs list -H -o mountpoint $keypkg_zpool >/dev/null 2>&1 ; then
            keypkg_zpool_mountpoint=$( zfs list -H -o mountpoint $keypkg_zpool )
            if [ -e ${keypkg_zpool_mountpoint}/${keypkg_file} ]; then
                # copy to standard location in tmpfs
                cat ${keypkg_zpool_mountpoint}/${keypkg_file} > ${keypkg_tmpfsdir}/${keypkg_file}
            fi
        fi
    fi
    if [ -n "$keypkg_ssh" ]; then
        for i in $keypkg_ssh ; do
            if [ ! -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
                # copy to standard location in tmpfs
                if ! ssh $keypkg_ssh_flags $i keypkg get > ${keypkg_tmpfsdir}/${keypkg_file} ; then
                    if [ -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
                        # exit code != 0, so this shouldn't exist
                        rm ${keypkg_tmpfsdir}/${keypkg_file}
                    fi
                    sleep 5
                fi
            fi
        done
    fi

    # Verify, then Decrypt then verify
    if [ -e ${keypkg_tmpfsdir}/${keypkg_file} ]; then
        # Verify package was for self
        if ! openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
                -in ${keypkg_tmpfsdir}/${keypkg_file} >/dev/null 2>/dev/null ; then
            echo "Verification of ${keypkg_tmpfsdir}/${keypkg_file} failed."
            exit 1
        fi
        openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
            -in ${keypkg_tmpfsdir}/${keypkg_file} 2>/dev/null \
                | openssl smime -decrypt -binary -nointern -recip $keypkg_cert -inkey $keypkg_key \
                | openssl smime -verify -CAfile $keypkg_cert -certfile $keypkg_cert \
                    -out ${keypkg_tmpfsdir}/geli_password.txt 2>/dev/null
        chmod 600 ${keypkg_tmpfsdir}/geli_password.txt
    fi

    # geli flags should be configured in rc.conf
    service geli start
    service geli2 start

    # unmount tmpfs so we get rid of the memory
    umount -f $keypkg_tmpfsdir

    if [ -n "$keypkg_zpool" ]; then
        if checkyesno keypkg_export && zpool list ${keypkg_zpool} >/dev/null 2>&1 ; then
            # export the pool on the USB thumbdrive
            zpool export ${keypkg_zpool}
        fi
    fi

    # zfs start to mount
    service zfs start

    # reload sshd in case we unlocked alternate config
    service sshd restart

    # start jails
    service iocage start

}

load_rc_config $name
run_rc_command "$1"
